export const InputTypes = {
  Text: "Text",
  Number: "Number",
  Date: "Date",
  Time: "Time",
  DateTime: "DateTime",
  Checkbox: "Checkbox",
  Radio: "Radio",
  Select: "Select",
  TextArea: "TextArea",
  File: "File",
  Image: "Image",
  Signature: "Signature",
  Custom: "Custom",
  CustomCheckbox: "CustomCheckbox",
  CustomRadio: "CustomRadio",
  CustomSelect: "CustomSelect",
  TextArea: "TextArea",
};
